fields:
  - handle: property_id
    field:
      type: text
      display: 'Property ID'
      validate:
        - required
        - integer
  - handle: handle
    field:
      type: hidden
      default: 'default'
#  - handle: service_account_credentials
#    field:
#      type: files
#      display: 'Client secret json file'
  - handle: widgets
    field:
      type: grid
      display: 'isapp-analytics::cp.WidgetsHeadline'
      instructions: 'isapp-analytics::cp.WidgetsInstructions'
      add_row: 'isapp-analytics::cp.AddWidget'
      fields:
        - handle: widget
          field:
            type: select
            display: 'isapp-analytics::cp.Widget'
            placeholder: 'isapp-analytics::cp.SelectWidget'
            options:
              visitors_and_page_views: 'isapp-analytics::cp.Visitors and page views'
              visitors_and_page_views_by_date: 'isapp-analytics::cp.Visitors and page views by date'
              total_visitors_and_pageviews: 'isapp-analytics::cp.Total visitors and pageviews'
              most_visited_pages: 'isapp-analytics::cp.Most visited pages'
              top_referrers: 'isapp-analytics::cp.Top Referrers'
              user_types: 'isapp-analytics::cp.User Types'
              top_browsers: 'isapp-analytics::cp.Top browsers'
              top_countries: 'isapp-analytics::cp.Top countries'
              top_operating_systems: 'isapp-analytics::cp.Top operating systems'
            validate:
              - required
        - handle: is_widget_enabled
          field:
            type: toggle
            display: 'isapp-analytics::cp.On Dashboard'
            default: false
            width: 25
        - handle: is_page_enabled
          field:
            type: toggle
            display: 'isapp-analytics::cp.On Analytics Page'
            default: false
            width: 25